const LANG = {
  fr: {
    play: "▶️ Jouer",
    profile: "👤 Profil",
    settings: "⚙️ Paramètres",
    shop: "🛍️ Boutique",
    pause: "⏸️ Pause",
    resume: "▶️ Reprendre",
    menu: "🏠 Menu",
    retry: "🔁 Rejouer",
    sound: "Sons activés",
    music: "Musique activée",
    theme: "Thème",
    lang: "Langue",
    reset: "🗑️ Réinitialiser les scores",
    best: "Meilleur score",
    coins: "VCoins",
    challenge: "🔥 Défi du jour",
    challenge_goal: "Survis au moins",
    challenge_accept: "🆚 Relever le défi",
    shop_title: "🎨 Boutique",
    badge_survivor: "🎖️ Survivant !"
  },
  en: {
    play: "▶️ Play",
    profile: "👤 Profile",
    settings: "⚙️ Settings",
    shop: "🛍️ Shop",
    pause: "⏸️ Pause",
    resume: "▶️ Resume",
    menu: "🏠 Menu",
    retry: "🔁 Retry",
    sound: "Sound enabled",
    music: "Music enabled",
    theme: "Theme",
    lang: "Language",
    reset: "🗑️ Reset scores",
    best: "Best score",
    coins: "VCoins",
    challenge: "🔥 Daily Challenge",
    challenge_goal: "Survive at least",
    challenge_accept: "🆚 Accept challenge",
    shop_title: "🎨 Shop",
    badge_survivor: "🎖️ Survivor!"
  },
  de: {
    play: "▶️ Spielen",
    profile: "👤 Profil",
    settings: "⚙️ Einstellungen",
    shop: "🛍️ Shop",
    pause: "⏸️ Pause",
    resume: "▶️ Fortsetzen",
    menu: "🏠 Menü",
    retry: "🔁 Wiederholen",
    sound: "Ton aktiviert",
    music: "Musik aktiviert",
    theme: "Thema",
    lang: "Sprache",
    reset: "🗑️ Punkte zurücksetzen",
    best: "Bester Score",
    coins: "VCoins",
    challenge: "🔥 Tages-Challenge",
    challenge_goal: "Überlebe mindestens",
    challenge_accept: "🆚 Herausforderung annehmen",
    shop_title: "🎨 Shop",
    badge_survivor: "🎖️ Überlebender!"
  },
  es: {
    play: "▶️ Jugar",
    profile: "👤 Perfil",
    settings: "⚙️ Ajustes",
    shop: "🛍️ Tienda",
    pause: "⏸️ Pausa",
    resume: "▶️ Continuar",
    menu: "🏠 Menú",
    retry: "🔁 Reintentar",
    sound: "Sonidos activados",
    music: "Música activada",
    theme: "Tema",
    lang: "Idioma",
    reset: "🗑️ Reiniciar puntuación",
    best: "Mejor puntuación",
    coins: "VCoins",
    challenge: "🔥 Desafío diario",
    challenge_goal: "Sobrevive al menos",
    challenge_accept: "🆚 Aceptar desafío",
    shop_title: "🎨 Tienda",
    badge_survivor: "🎖️ Superviviente!"
  },
  nl: {
    play: "▶️ Spelen",
    profile: "👤 Profiel",
    settings: "⚙️ Instellingen",
    shop: "🛍️ Winkel",
    pause: "⏸️ Pauze",
    resume: "▶️ Hervatten",
    menu: "🏠 Menu",
    retry: "🔁 Opnieuw",
    sound: "Geluid aan",
    music: "Muziek aan",
    theme: "Thema",
    lang: "Taal",
    reset: "🗑️ Scores resetten",
    best: "Beste score",
    coins: "VCoins",
    challenge: "🔥 Dagelijkse uitdaging",
    challenge_goal: "Overleef minstens",
    challenge_accept: "🆚 Uitdaging accepteren",
    shop_title: "🎨 Winkel",
    badge_survivor: "🎖️ Overlever!"
  },
  it: {
    play: "▶️ Gioca",
    profile: "👤 Profilo",
    settings: "⚙️ Impostazioni",
    shop: "🛍️ Negozio",
    pause: "⏸️ Pausa",
    resume: "▶️ Riprendi",
    menu: "🏠 Menu",
    retry: "🔁 Riprova",
    sound: "Suoni attivati",
    music: "Musica attivata",
    theme: "Tema",
    lang: "Lingua",
    reset: "🗑️ Reset punteggi",
    best: "Miglior punteggio",
    coins: "VCoins",
    challenge: "🔥 Sfida del giorno",
    challenge_goal: "Sopravvivi almeno",
    challenge_accept: "🆚 Accetta la sfida",
    shop_title: "🎨 Negozio",
    badge_survivor: "🎖️ Sopravvissuto!"
  },
  pt: {
    play: "▶️ Jogar",
    profile: "👤 Perfil",
    settings: "⚙️ Configurações",
    shop: "🛍️ Loja",
    pause: "⏸️ Pausar",
    resume: "▶️ Retomar",
    menu: "🏠 Menu",
    retry: "🔁 Repetir",
    sound: "Som ativado",
    music: "Música ativada",
    theme: "Tema",
    lang: "Idioma",
    reset: "🗑️ Reiniciar pontuação",
    best: "Melhor pontuação",
    coins: "VCoins",
    challenge: "🔥 Desafio diário",
    challenge_goal: "Sobreviva por pelo menos",
    challenge_accept: "🆚 Aceitar desafio",
    shop_title: "🎨 Loja",
    badge_survivor: "🎖️ Sobrevivente!"
  },
  ja: {
    play: "▶️ プレイ",
    profile: "👤 プロフィール",
    settings: "⚙️ 設定",
    shop: "🛍️ ショップ",
    pause: "⏸️ 一時停止",
    resume: "▶️ 再開",
    menu: "🏠 メニュー",
    retry: "🔁 リトライ",
    sound: "サウンド有効",
    music: "音楽有効",
    theme: "テーマ",
    lang: "言語",
    reset: "🗑️ スコアをリセット",
    best: "ベストスコア",
    coins: "Vコイン",
    challenge: "🔥 今日のチャレンジ",
    challenge_goal: "少なくとも生き延びろ",
    challenge_accept: "🆚 チャレンジ開始",
    shop_title: "🎨 ショップ",
    badge_survivor: "🎖️ サバイバー！"
  }
};
